### ISSUE TITLE
66. (34 pontos) Implementar Monitoramento e Alertas com Prometheus e Grafana

### ISSUE THREAD

**Issue by RamonSantos10** [RamonSantos10/avaliacao2-tp2-stockapp#75]
66. **(34 pontos) Implementar Monitoramento e Alertas com Prometheus e Grafana**
    - **Descrição**: Configure monitoramento e alertas usando Prometheus e Grafana para monitorar a saúde do sistema.
    - **Código**:
      ```yaml
      # Configuração de exemplo para Prometheus
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'aspnetcore'
          static_configs:
            - targets: ['localhost:5000']
      ```
